name: 'react-scatter-graphy storybook deploy'

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: yarn
      - uses: chromaui/action@v1
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          token: ${{ secrets.GITHUB_TOKEN }}
          script: sed -i 's/CHROMATIC_HOMEPAGE_PLACEHOLDER/https:\/\/chromatic.com\/builds\/${{ env.CHROMATIC_BUILD_ID }}\/storybook/g' package.json
