name: 'react-scatter-graphy storybook deploy and npm publish'

on:
  push:
    branches:
      - deploy

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          persist-credentials: false
          ref: ${{ github.head_ref }}
          push: true
      - run: yarn
      - run: mkdir -p dist
      - uses: chromaui/action@v1
        id: chromatic
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          token: ${{ secrets.GITHUB_TOKEN }}
      - run: |
          npm config set '//registry.npmjs.org/:_authToken' ${{ secrets.NPM_AUTH_TOKEN }}
          npm config set access public
      - run: |
          sed -i "s|CHROMATIC_HOMEPAGE|${{ steps.chromatic.outputs.storybookUrl }}|" package.json
      - run: yarn publish:npm-outDir
      - run: cp -R build/* dist/
      - uses: LasyIsLazy/github-upload-action@v0.1.0
        with:
          access-token: ${{ secrets.GIT_AUTH_TOKEN }}
          file-path: dist/
          owner: rjsduf0503
          repo: react-scatter-graphy
          remote-dir: dist
          commit-message: 'build: automate deploy dist'
          branch-name: dist-build
